/**
 * Manifest Generator -- creates SYSTEM.md from DB state.
 *
 * SYSTEM.md is auto-generated and never hand-edited. It gives the assistant
 * full awareness of its own system at session start.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type Database from "better-sqlite3";
import type { FamiliarConfig } from "./config.js";
import type { Agent } from "./agents/types.js";
import type { Schedule } from "./schedules/types.js";
import type { Tool } from "./tools/types.js";
import type { Project } from "./projects/types.js";

export interface ManifestOptions {
  personaPath: string;
  db: Database.Database;
  config: FamiliarConfig;
}

export function generateManifest(opts: ManifestOptions): void {
  const { personaPath, db, config } = opts;
  const lines: string[] = [];
  const now = new Date().toISOString();

  lines.push("# SYSTEM.md -- Auto-Generated System Manifest");
  lines.push("");
  lines.push(`> Generated: ${now}`);
  lines.push("> Do not edit this file. It is regenerated on startup and by `familiar manifest`.");
  lines.push("");

  // Service info
  lines.push("## Service");
  lines.push("");
  lines.push(`- **Database**: ~/.familiar/familiar.db`);
  const publicUrl = config.webhooks?.publicUrl ?? "";
  if (publicUrl) {
    lines.push(`- **Dashboard**: ${publicUrl}`);
  }
  lines.push(`- **API**: http://localhost:${config.webhooks?.port ?? 3002}/api/`);
  lines.push(`- **Model**: ${config.claude.model ?? "sonnet"}`);
  lines.push(`- **Working Directory**: ${config.claude.workingDirectory}`);
  lines.push("");

  // Agents
  const agents = safeQuery<Agent>(db, "SELECT * FROM agents ORDER BY name ASC");
  if (agents.length > 0) {
    lines.push("## Agents");
    lines.push("");
    lines.push("| ID | Name | Model | Budget | Project | Enabled |");
    lines.push("|---|---|---|---|---|---|");
    for (const a of agents) {
      const budget = a.daily_budget_usd != null ? `$${a.daily_budget_usd}` : "--";
      const enabled = a.enabled ? "yes" : "no";
      const project = a.project_id ?? "--";
      lines.push(`| ${a.id} | ${a.name} | ${a.model} | ${budget} | ${project} | ${enabled} |`);
    }
    lines.push("");
  }

  // Schedules
  const schedules = safeQuery<Schedule & { agent_name?: string }>(
    db,
    `SELECT s.*, a.name as agent_name
     FROM schedules s LEFT JOIN agents a ON s.agent_id = a.id
     ORDER BY s.agent_id, s.id`,
  );
  if (schedules.length > 0) {
    lines.push("## Schedules");
    lines.push("");
    lines.push("| Agent | Schedule | Timezone | Name | Enabled |");
    lines.push("|---|---|---|---|---|");
    for (const s of schedules) {
      const agentLabel = s.agent_name ?? s.agent_id;
      const name = s.name ?? "--";
      const enabled = s.enabled ? "yes" : "no";
      lines.push(`| ${agentLabel} | \`${s.schedule}\` | ${s.timezone} | ${name} | ${enabled} |`);
    }
    lines.push("");
  }

  // Tools
  const tools = safeQuery<Tool>(db, "SELECT * FROM tools ORDER BY type, name ASC");
  if (tools.length > 0) {
    lines.push("## Tools");
    lines.push("");
    lines.push("| ID | Name | Type | Command | Enabled |");
    lines.push("|---|---|---|---|---|");
    for (const t of tools) {
      const cmd = t.cli_command ?? t.binary_path ?? "--";
      const enabled = t.enabled ? "yes" : "no";
      lines.push(`| ${t.id} | ${t.name} | ${t.type} | ${cmd} | ${enabled} |`);
    }
    lines.push("");
  }

  // Projects
  const projects = safeQuery<Project>(db, "SELECT * FROM projects ORDER BY name ASC");
  if (projects.length > 0) {
    lines.push("## Projects");
    lines.push("");
    lines.push("| ID | Name | Path | Enabled |");
    lines.push("|---|---|---|---|");
    for (const p of projects) {
      const path = p.path ?? "--";
      const enabled = p.enabled ? "yes" : "no";
      lines.push(`| ${p.id} | ${p.name} | ${path} | ${enabled} |`);
    }
    lines.push("");
  }

  // Architecture summary
  lines.push("## Architecture");
  lines.push("");
  lines.push("- **Scheduler**: CronScheduler reads agents + schedules from DB, spawns `claude -p` processes");
  lines.push("- **Bridge**: Telegram <-> Claude CLI session management with message splitting");
  lines.push("- **Delivery Queue**: Retry-safe message delivery to Telegram with persistence");
  lines.push("- **Spawn Queue**: File-based queue at ~/.familiar/spawn-queue/ for sub-agent requests");
  lines.push("- **Agent Workspace**: Persistent state/output/memory dirs per agent at ~/.familiar/agents/");
  lines.push("- **Memory Store**: Semantic search via OpenAI embeddings (index with `familiar index-memory`)");
  lines.push("");

  // API endpoints
  lines.push("## API Endpoints");
  lines.push("");
  lines.push("```");
  lines.push("GET  /health                  Health check");
  lines.push("GET  /api/agents/crud         List persistent agents");
  lines.push("GET  /api/schedules           List schedules");
  lines.push("GET  /api/tools               List tools");
  lines.push("GET  /api/projects            List projects");
  lines.push("GET  /api/tasks               List tasks");
  lines.push("GET  /api/tasks/next?agent=ID Get next task for agent");
  lines.push("GET  /api/cron/jobs           List cron jobs with state");
  lines.push("GET  /api/runs                Fleet-wide run history");
  lines.push("GET  /api/cost/summary        Per-agent cost totals");
  lines.push("GET  /api/memory/search?q=    Semantic memory search");
  lines.push("POST /hooks/wake              Inject message into session");
  lines.push("POST /hooks/agent             Run isolated agent turn");
  lines.push("```");
  lines.push("");

  // Stats
  lines.push("## Stats");
  lines.push("");
  lines.push(`- Agents: ${agents.length}`);
  lines.push(`- Schedules: ${schedules.length}`);
  lines.push(`- Tools: ${tools.length}`);
  lines.push(`- Projects: ${projects.length}`);

  const taskCount = safeScalar(db, "SELECT COUNT(*) as count FROM tasks");
  if (taskCount !== null) {
    lines.push(`- Tasks: ${taskCount}`);
  }

  const runCount = safeScalar(db, "SELECT COUNT(*) as count FROM cron_runs WHERE started_at > datetime('now', '-24 hours')");
  if (runCount !== null) {
    lines.push(`- Cron runs (24h): ${runCount}`);
  }
  lines.push("");

  const content = lines.join("\n");
  writeFileSync(join(personaPath, "SYSTEM.md"), content, "utf-8");
}

function safeQuery<T>(db: Database.Database, sql: string): T[] {
  try {
    return db.prepare(sql).all() as T[];
  } catch {
    return [];
  }
}

function safeScalar(db: Database.Database, sql: string): number | null {
  try {
    const row = db.prepare(sql).get() as { count: number } | undefined;
    return row?.count ?? null;
  } catch {
    return null;
  }
}
